### ISSUE TITLE
Doesn't start clicking in game...

### ISSUE THREAD

**Issue by jdcooper901** [SnoopLawg/PyAutoRaid#4]
Log shows its trying to close an ad over and over again. Tried running multiple times.
![image](https://github.com/SnoopLawg/PyAutoRaid/assets/81704500/cbf4232c-da7e-4452-a379-5e007109363e)

**Comment by SnoopLawg** [comment]
Hi sorry, I am just now able to get back to this project. Could you show me a screenshot possibly of a dialog box popup? Also, what system are you running this on? Windows? Also if you could tell me which version, that would help too. It is untested on anything other than Windows 10 and a 1920 x 1080 Monitor, so any additional info would help :) Thanks
